name: Dividir PDF desde n8n

on:
  repository_dispatch:
    types: [split-pdf]

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el script de división
        env:
          GDRIVE_SA_KEY: ${{ secrets.GDRIVE_SA_KEY }}
          FILE_ID: ${{ github.event.client_payload.fileId }}
          START_PAGES: ${{ toJSON(github.event.client_payload.startPages) }}
          OUTPUT_FOLDER_ID: ${{ github.event.client_payload.outputFolderId }}
        run: python split_pdf.py
