name: Dividir PDF (OAuth usuario)

on:
  repository_dispatch:
    types: [split-pdf]

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib pypdf

      - name: Run splitter
        env:
          GOOGLE_CLIENT_ID:     ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          FILE_ID: ${{ github.event.client_payload.fileId }}
          START_PAGES: ${{ toJSON(github.event.client_payload.startPages) }}
          OUTPUT_FOLDER_ID: ${{ github.event.client_payload.outputFolderId }}
          NAME_PREFIX: ${{ github.event.client_payload.namePrefix }}
        run: python split_pdf.py

